theme: jekyll-theme-minimal
title: dill & fennel
description: a blog
author:
    name: "brook shelley"
    email: "brookshelley+blog@gmail.com"
gems:
  - jekyll-feed
plugins:
  - jekyll-redirect-from
