theme: jekyll-swiss
title: dill & fennel
description: a blog
author:
    name: "brook shelley"
    email: "brookshelley+blog@gmail.com"
gems:
  - jekyll-feed
  - jekyll-swiss
plugins:
  - jekyll-redirect-from
