theme: jekyll-theme-minimal
title: brookshelley 
dot com
description: my work and media reviews
author:
    name: "brook shelley"
    email: "brookshelley+blog@gmail.com"
gems:
  - jekyll-feed
plugins:
  - jekyll-redirect-from
